### ISSUE TITLE
Max Sizing of the pikachu

### ISSUE THREAD

**Issue by Thanatermesis** [jeanguyomarch/pikalogy#4]
Nice theme! :) I was trying it and I found it funny!, maybe I'll add a package for the elive repo too, if you are ok

Actually I found a small bug, if you resize the fonts of the terminology (ctrl + wheel) you don't see the pikachu to increase the size, maybe you should set some "max" values to at least the double if you cannot use bigger images of the picachu (so the user would like to "appreciate" the image in more details), also in any case it doesn't looks to fit correctly with the terminal if the image is too small (smaller than the fonts)

Have a nice day!
Thanatermesis

**Comment by Thanatermesis** [comment]
Mmmh, in the same time when the fonts are very small (less than 10 px) the pikachu looks huge (but is not really annoying like this)

**Comment by jeanguyomarch** [comment]
Hi,

thanks a lot for your interest in pikalogy :)
I never had the opportunity to try out Elive, but it would be very nice if you could package pikalogy some day (if the Pikachu's license is not an issue).

Commit cb5c036 should fix the scaling problem. Pikachu will still look a bit too big with very small fonts, but I think it is acceptable.

Thanks again for the report :)
