### ISSUE TITLE
error lign 3550 pikalogy.edc

### ISSUE THREAD

**Issue by aureleS** [jeanguyomarch/pikalogy#5]
You forgot the third argument of action. my guess it's 0.0 !

**Comment by jeanguyomarch** [comment]
Good catch! 
Did you spot this mistake just by reading at the code or is there a tool somewhere I am not aware of?

**Comment by aureleS** [comment]
I just tried to make it on my Debian, and the error pooped !

**Comment by jeanguyomarch** [comment]
Ok, you might have an old version of edje_cc then.
Anyway, thank you for the report :-)
