### ISSUE TITLE
Sound doesn't works for me

### ISSUE THREAD

**Issue by Cdiez50** [jeanguyomarch/pikalogy#7]
Hy ! And a huge thanks for your work ! :+1: 

I actually meet an issue while installing pikalogy. The sound does not seems to work.

I define **Definition** like this : 
**DEFINITIONS	:= -DWITH_SOUND**

And then I `sudo make install`

Here is the MakeFile

```
PREFIX		:= /usr/local
EDJE_CC		:= edje_cc
TERMINOLOGY	:= terminology

V		:= 0
AT_0		:= @
AT_1		:=
AT		:= $(AT_$(V))

EDJE_VERBOSE_0	:=
EDJE_VERBOSE_1	:= -v
EDJE_VERBOSE	:= $(EDJE_VERBOSE_$(V))

#DEFINITIONS	?=
DEFINITIONS	:= -DWITH_SOUND

.PHONY: all clean install uninstall test

all: pikalogy.edj

pikalogy.edj: pikalogy.edc default_colors.in.edc
	@echo "  EDJ       $@"
	$(AT)$(EDJE_CC) $(EDJE_VERBOSE_1) $(DEFINITIONS) -id images -sd sounds pikalogy.edc pikalogy.edj

clean:
	$(RM) pikalogy.edj

install: pikalogy.edj
	@echo "  INSTALL   $<"
	$(AT)install -m 0644 pikalogy.edj /home/$USER/.config/terminology/themes/

uninstall:
	$(RM) /home/$USER/.config/terminology/themes/pikalogy.edj

test: pikalogy.edj
	$(TERMINOLOGY) --theme=./pikalogy.edj

```

Did I make something wrong ?

Thanks !

**Comment by jeanguyomarch** [comment]
Hi, thanks for your interest in pikalogy :-)

Actually, you did nothing wrong... I think there is an edje_cc issue here.
I have to investigate exactly what is going on. Meanwhile, you can apply the patch attached:

[0001-pikalogy-force-sound-enabled.txt](https://github.com/jeanguyomarch/pikalogy/files/511130/0001-pikalogy-force-sound-enabled.txt)

```bash
cd /path/to/pikalogy
git am < /path/to/downloaded/0001-pikalogy-force-sound-enabled.txt
```
It will enable the audio by dropping the conditionals. You can just then run `make` and `sudo make install`.

As a sidenote, you could have compiled with:
```bash
make DEFINITIONS="-DWITH_SOUND"
```
to avoid modifying the Makefile.


I'll investigate the bug and keep you updated.
Thanks for reporting :-)

**Comment by jeanguyomarch** [comment]
Mhh actually there is much simpler. Can you please try this:

```bash
make DEFINITIONS="-DWITH_SOUND=1"
```

I exepcted epp to act like cpp there. If it works for you, I will update the README.

**Comment by Cdiez50** [comment]
Hey ! Thanks for your answer ! Actually I made 
`cd /path/to/pikalogy
git am < /path/to/downloaded/0001-pikalogy-force-sound-enabled.txt`

And then `make install` and it seems now to work find ! :smile: 

I retry on another Arch machine I have without doing the `git am` but it was not working too...

Anw, I put this issue as solved :smile: 

Big thanks ! :+1:

**Comment by jeanguyomarch** [comment]
Nice :-)
